#!/usr/bin/env python

# Usage:
# Linux/Unix/Mac: ./create-dashboard --help
# Windows: python create-dashboard --help

from create_dashboard.create_dashboard import main

if __name__ =='__main__':
    main()
